extern crate time;
extern crate libc;

pub mod time_tests;
pub mod debug_and_fmt_tests;
pub mod lifetime_tests;
pub mod ownership_and_borrowing_tests;
pub mod unknown_tests_1;
pub mod parser_tests;
pub mod macro_tests;
pub mod box_tests;
pub mod hash_map_tests;
pub mod iter_tests;
pub mod drop_tests;
pub mod if_let_tests;
pub mod closure_tests;
pub mod any_tests;
pub mod fmt_tests;
pub mod ffi_tests;
